export const items_per_page = 7;
export const message_index = 'm';
export const message_id_prefix = 'a_';
export const room_index = 'r';
export const room_id_prefix = 'r_';
export const tag_index = 't';
export const tag_id_prefix = 't_';
export const replies_index_name = 'rs';
export const replied_index_name = 'rd';
export const top_level_messages_name = 't';
export const protected_routes = [/\/edit/, /\/u\/\w+\/c/, /\/i\/add/, /\/m\/m/];
export const embedding_model = 'text-embedding-3-large';
export const embedding_field_name = 'v';
export const embedding_dimension = 3072;
export const ids_hash = 'ids';
export const user_id_prefix = 'u_';
export const user_index = 'u';
export const feedback_index = 'f';
export const feedback_id_prefix = 'f_';

export const bid_index = 'b';
export const bid_id_prefix = 'b_'
export const bid_last_id = 'bid_last_id'
